<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPDoxLLJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPDoxLLJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPDoxLLJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPDoxLLJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPDoxLLJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'PDoxLLJ',
    'container.build_id' => 'f7edcb9e',
    'container.build_time' => 1647203398,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPDoxLLJ');
